version: '3.8'
services:
  CodeGen:
    image: prashrex/codegen
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" 
    tty: true
    stdin_open: true

  watchtower:
    image: containrrr/watchtower
    command: --interval 15 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true

  redis:
    image: redis:3.0
    restart: always
    ports:
      - "6379:6379"

networks:
  express_nw:
    driver: bridge
