version: '3.8'

services:
  CodeGen:
    image: prashrex/codegen
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000" 
    tty: true
    stdin_open: true
