version: '3.8'
services:
  Dashboard:
    image: prashrex/codegen
    container_name: dashboard-react
    restart: always
    build: 
      context: ./dashboard
      dockerfile: Dockerfile
    volumes:
      - ./dashboard:/react-docker:delegated
      - /node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  CodeGen:
    image: prashrex/codegen
    container_name: codegen
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" 
    expose:
      - 8000
    tty: true
    stdin_open: true

  watchtower:
    image: containrrr/watchtower
    command: --interval 15 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true

  redis:
    image: redis:3.0
    restart: always
    ports:
      - "6379:6379"


networks:
  llm-webapp-network:
    driver: bridge