"""conversation_table

Revision ID: 9e1181203643
Revises: 56fb0f6162bb
Create Date: 2023-07-28 15:47:54.204024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1181203643'
down_revision = '56fb0f6162bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('conv_id', sa.String(), nullable=False),
    sa.Column('qa', sa.String(), nullable=False),
    sa.Column('dtime', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('conv_id')
    )
    op.drop_table('messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('msg_id', sa.VARCHAR(), nullable=False),
    sa.Column('ques', sa.VARCHAR(), nullable=False),
    sa.Column('ans', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('msg_id')
    )
    op.drop_table('conversation')
    # ### end Alembic commands ###
