name: pipeline

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    name: 'build && push image to Docker Hub'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: 'Setup Docker Buildx'
        uses: docker/setup-buildx-action@v2

      - name: 'Docker Login'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Build and push API'
        id: build-push-api
        uses: docker/build-push-action@v2
        with:
          context: ./ 
          file: ./Dockerfile
          push: true
          tags: prashrex/codegen:latest